"""
NemoAgent critic for validating Phinance outputs against source data.

Uses NemoAgent (already warm on GPU 0) as a QA reviewer to catch:
- Factual errors (numbers that don't match source)
- Unsupported claims (insights without data backing)
- Missing obvious patterns
- Illogical drain classifications
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, Tuple

logger = logging.getLogger(__name__)


CRITIC_SYSTEM_PROMPT = """You are a financial analysis QA reviewer. Your job is to validate 
that an AI's financial insights are accurate and supported by the source data.

You will receive:
1. SOURCE DATA: The ground truth (pre-calculated by Python)
2. LLM OUTPUT: The insights generated by another AI

Your task: Check if the LLM output is accurate, supported, and complete.

Respond with JSON only:
{
  "pass": true/false,
  "issues": ["list of factual errors or unsupported claims"],
  "missing_insights": ["obvious patterns the LLM missed"],
  "risk_flags": ["anything that could mislead the user"]
}
"""

CRITIC_USER_TEMPLATE = """## SOURCE DATA (ground truth - calculated by Python)
{source_data}

## LLM OUTPUT (to validate)
{llm_output}

## Validation Checklist
1. ACCURACY: Do the insights reference correct numbers from source?
2. SUPPORT: Is every claim backed by source data?
3. COMPLETENESS: Any obvious pattern in source data that's missing from insights?
4. LOGIC: If drain_verifications exist, are the is_drain judgments reasonable?
5. ACTIONABLE: Are recommendations specific enough to act on?

Respond with JSON only."""


def validate_phinance_output(
    source_stats: Dict[str, Any], phinance_output: Dict[str, Any]
) -> Tuple[bool, Dict[str, Any]]:
    """Validate Phinance output against source statistics using NemoAgent.

    Args:
        source_stats: Python-calculated financial statistics (ground truth)
        phinance_output: Full Phinance response including insights

    Returns:
        Tuple of (passed: bool, validation_result: dict)
        validation_result contains: pass, issues, missing_insights, risk_flags
    """
    from models import _ENDPOINTS, _build_chat_payload, _dispatch_request

    source_summary = {
        "total_spent": source_stats.get("total_spent"),
        "transaction_count": source_stats.get("transaction_count"),
        "categories": source_stats.get("categories"),
        "top_merchants": source_stats.get("top_merchants", [])[:5],
        "hidden_drains": source_stats.get("hidden_drains", [])[:5],
    }

    llm_summary = {
        "insights": phinance_output.get("insights", []),
        "recommendations": phinance_output.get("recommendations", []),
        "potential_savings": phinance_output.get("potential_savings"),
        "drain_verifications": phinance_output.get("drain_verifications"),
    }

    user_prompt = CRITIC_USER_TEMPLATE.format(
        source_data=json.dumps(source_summary, indent=2),
        llm_output=json.dumps(llm_summary, indent=2),
    )

    endpoint = _ENDPOINTS["nemotron"]
    payload = _build_chat_payload(
        endpoint, user_prompt, system_prompt=CRITIC_SYSTEM_PROMPT
    )

    try:
        raw_response = _dispatch_request(endpoint, payload, prompt_source="critic")

        from utils.llm_validation import extract_json_from_response

        clean_json = extract_json_from_response(raw_response)
        result = json.loads(clean_json)

        passed = result.get("pass", False)
        if not passed:
            issues = result.get("issues", [])
            logger.warning(f"Critic validation failed: {issues[:2]}")

        return passed, result

    except Exception as e:
        logger.error(f"Critic validation error: {e}")
        return True, {
            "pass": True,
            "issues": [],
            "missing_insights": [],
            "risk_flags": [f"Critic unavailable: {str(e)}"],
        }


def critic_and_retry(
    source_stats: Dict[str, Any],
    phinance_output: Dict[str, Any],
    max_retries: int = 1,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Run critic validation with optional retry on failure.

    If critic finds issues on first pass, re-runs Phinance with feedback.

    Args:
        source_stats: Python-calculated ground truth
        phinance_output: Initial Phinance response
        max_retries: Number of retry attempts (default 1)

    Returns:
        Tuple of (final_output, validation_result)
    """
    passed, validation = validate_phinance_output(source_stats, phinance_output)

    if passed or max_retries <= 0:
        return phinance_output, validation

    issues = validation.get("issues", [])
    if not issues:
        return phinance_output, validation

    logger.info(f"Critic found {len(issues)} issues, requesting Phinance retry")

    from models import call_phinance

    feedback = f"\n\nPREVIOUS RESPONSE HAD ISSUES:\n" + "\n".join(
        f"- {i}" for i in issues[:3]
    )
    feedback += "\n\nPlease fix these issues in your response."

    retry_payload = json.dumps({**source_stats, "_feedback": feedback})

    try:
        retry_response, _ = call_phinance(retry_payload)
        retry_output = json.loads(retry_response)

        retry_passed, retry_validation = validate_phinance_output(
            source_stats, retry_output
        )

        if retry_passed:
            logger.info("Retry passed critic validation")
            return retry_output, retry_validation
        else:
            logger.warning("Retry still has issues, returning original")
            return phinance_output, validation

    except Exception as e:
        logger.error(f"Retry failed: {e}")
        return phinance_output, validation
